# Generated by Django 3.2.9 on 2022-04-06 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_courses', models.CharField(max_length=150, unique=True, verbose_name='Название курса')),
                ('description_of_courses', models.TextField(verbose_name='Описание курса')),
                ('dates_of_event', models.DateField(verbose_name='Дата проведения')),
                ('mentor', models.CharField(max_length=255, verbose_name='Ментор')),
                ('course_completion_rate', models.IntegerField(blank=True, verbose_name='Процент освоения темы')),
            ],
        ),
        migrations.CreateModel(
            name='LessonsBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_lessons', models.IntegerField(unique=True, verbose_name='Номер блока')),
                ('lessons_title', models.CharField(max_length=250, verbose_name='Название блока')),
                ('goals_at_the_end', models.TextField(blank=True, verbose_name='Цель по окончании')),
            ],
        ),
        migrations.CreateModel(
            name='Subthemes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtheme_title', models.CharField(max_length=255, verbose_name='Название подтемы')),
                ('comments', models.TextField(blank=True, verbose_name='Комментарии')),
                ('lessons_block_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.lessonsblock')),
            ],
        ),
    ]
