# Generated by Django 3.2.9 on 2022-04-06 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subthemes',
            name='lessons_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lessons.lesson'),
        ),
        migrations.AddField(
            model_name='courses',
            name='hometasks_list_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='lessons.lessonslist', verbose_name='Список ДЗ'),
        ),
        migrations.AddField(
            model_name='courses',
            name='lessons_block_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='courses.lessonsblock', verbose_name='Блок занятий'),
        ),
        migrations.AddField(
            model_name='courses',
            name='lessons_list_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lessons.lessonslist', verbose_name='Список уроков'),
        ),
        migrations.AddField(
            model_name='courses',
            name='subthemes_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='courses.subthemes', verbose_name='Подтемы'),
        ),
    ]
