# Generated by Django 3.2.9 on 2022-04-06 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subthemes',
            name='lessons_block_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='courses.lessonsblock'),
        ),
    ]
